name: insurance_hack

services:
  backend:
    build: .
    ports:
      - 80:80
    networks:
      - insurance
  postgres:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    networks:
      - insurance
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: default_db

volumes:
  postgres-data:

networks:
  insurance: